### ISSUE TITLE
Manage Palette is not available on Bluemix.

### ISSUE THREAD

**Issue by mylind** [ibmets/node-red-bluemix-starter#15]
The function "Manage Palette looks not available on Bluemix. More clients meet the similar issue about "Manage Palette.  Please help to check them:
1. Sometimes, the nodes that installed via "Manage Palette" are lost after restarting the app.
2. Sometimes, the nodes that installed via "Manage Palette" are disabled after restarting the app and can not be enabled.

**Comment by knolleary** [comment]
Hi, thanks for raising this. We thought we had resolved this issue with the update we did in March. Can I confirm when you created your Node-RED instance?

It would be useful if you could share the Node-RED log output from when Node-RED starts. It will log details of trying to reinstall those added modules. If that is failing, we need to see the log to understand why.
