### ISSUE TITLE
Update Nano dependency

### ISSUE THREAD

**Issue by glynnbird** [ibmets/node-red-bluemix-starter#35]
This project depends on Nano (the Apache CouchDB Node.js library) version 6.2 which was released in January 2016. You may want to upgrade this dependency to either:

- nano 8.1.0 (the latest) 
- nodejs-cloudant (the official Cloudant library which wraps Nano and adds Cloudant-specific functions)

As of [June 1st](https://www.ibm.com/cloud/blog/announcements/ibm-cloudant-security-update-tls-1-2-and-service-endpoints) Cloudant is switching to TLS 1.2+ only. Using the latest nodejs-cloudant library is the best guarantee of the code continuing to work after this date.

**Comment by knolleary** [comment]
@glynnbird thanks for the heads up. Although that doesn't give us much time to update. There are a *lot* of existing Node-RED instances on IBM Cloud that will still be using this older version. Will they all break on June 1st?

**Comment by knolleary** [comment]
Nano updated to 8.1.0 - have tested and it doesn't require any code changes.

Still need to update the boilerplate in the catalog itself... but that's another repo.
