### ISSUE TITLE
Issue for multi-instances

### ISSUE THREAD

**Issue by mylind** [ibmets/node-red-bluemix-starter#7]
I found an issue for node-red-bluemix-starter. If your Node-Red app has multi-instances, then your new flow deployment can not be enabled. You have to restart the whole app to enable it. It is very easy to reproduce it.

Single instance works well.

**Comment by knolleary** [comment]
Correct. This is a limitation of running Node-RED as-is in Bluemix.  If you want to run multiple instances you need to either restart, or scale back to a single instance before deploying new flows, then scale back out.

We have some ideas around making this easier, but will require an external service to coordinate the deploys across all instances.
